eureka-server:
  hostname: localhost
  port: 8761

eureka:
  client:
    service-url:
      default-zone: http://${eureka-server.hostname}:${eureka-server.port}/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hello # 服务与服务之间相互调用一般都是通过这个名称
