server:
  port: 8888

eureka-server:
  hostname: localhost
  port: 8761

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XiDian-ChenMiao/spring-cloud-master # 仓库地址
          search-paths: config # 仓库路径
          username:  # 访问用户名
          password:  # 访问密码
      label: master # 仓库分支
eureka:
  client:
    service-url:
      default-zone: http://${eureka-server.hostname}:${eureka-server.port}/eureka/





